### ISSUE TITLE
Rebuild the project with requests

### ISSUE THREAD

**Issue by panbofeng** [kcajc/usvisa-ca#17]
Hi kcaja,

Thanks for your job.
I also did a script with selenium three years ago and it worked well. However, in 2024, it seems there are fewer visa slots at the U.S. Embassy in Canada. Then my visa got expired, and my family needs the visa as soon as possible, so I had to find a better way to get a close slot.

Obviously, selenium is slower than requests, so I tried to use requests to invoke their APIs directly. However, I failed for the login process and the reschedule process. Even if I send the correct token and Cookie, it returns "login needed". More interesting is that, the APIs between these two steps can be invoked well, it means after using selenium to do the login and then using the obtained cookie to search the available slots by requests is possible. I think the website may have used some other tricks to prevent the logins and reschedule function by invoking the APIs directly. Could you try to do it on your side? Or maybe we can discuss with it.

Then, another big problem is that the website has risk control system. It means that if you refresh too often, you will be banned from the website for around 5 hours. This leads to the fact that even if you can go through the whole process with requests, it doesn't make much sense. As it stands now, you can't get slots unless you refresh every second, because the slots are really rare these days, but if you do it every second, you will be banned immediately. And I know there are some people and even companies that profit from getting a slot in Canada, and they have a very high success rate, so I don't know how they solve this problem. Do you have any idea about this？

**Comment by kcajc** [comment]
>  However, I failed for the login process and the reschedule process. Even if I send the correct token and Cookie, it returns "login needed".

I personally haven't tried using requests for login simply because I saw the hCaptcha icon so I thought this probably requires more effort. However, in my rewrite earlier this year I did use request for fetching available slots which works fine. If you really want to write login with requests, I would suggest looking into the headers in a request from your code vs a real request from a browser. In particular I noticed they have checks against `User-Agent`, `X-CSRF-Token`, `X-Requested-With` and obviously `Cookie`.

> another big problem is that the website has risk control system.

During my testing earlier this year, as long as you get a new session every 30 minutes and fetch the dates every minute you should not have a problem with the rate limit. 

> they have a very high success rate

Well if it's a business then they can probably just get like 10 accounts booked and have a few EC2 instances with different  IPs fetching the dates and fetch the dates at a high rate. I don't think there's anything sophisticated there, it's just a matter of engineering effort. Unfortunately this is the best way to get you a slot if you really need one soon.

If you wanna chat more about this feel free to send me your Discord or whatever via the website in my bio.
